title: Sweet #博客标题
description: 一个沙雕程序猿的博客 #博客描述
keywords: blog,css,html,php #博客关键字
author: "Sweet"

#title hide and show
hide: (つェ⊂)我藏好啦
show: ´∇｀ 呀被发现啦~

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "hydrogen.atlinker.cn" # change this to the base hostname & protocol for your site
buildtime: "1514736000" #博客建立时的时间戳 可进入https://tool.lu/timestamp/将博客建立时的日期转换成时间戳
           #The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.

PJAX: true #启用PJAX，会与评论系统冲突（如不用评论系统建议开启）

paginate: 8 #同时显示的最大文章数，超过自动分页
paginate_path: "page:num"

background: http://image.baidu.com/search/detail?ct=503316480&z=undefined&tn=baiduimagedetail&ipn=d&word=hello%2C%20world&step_word=&ie=utf-8&in=&cl=2&lm=-1&st=undefined&hd=undefined&latest=undefined&copyright=undefined&cs=2628225940,3347879136&os=3135520123,1216661704&simid=0,0&pn=2&rn=1&di=63910&ln=665&fr=&fmq=1568124646556_R&fm=&ic=undefined&s=undefined&se=&sme=&tab=0&width=undefined&height=undefined&face=undefined&is=0,0&istype=0&ist=&jit=&bdtype=0&spn=0&pi=0&gsm=0&objurl=http%3A%2F%2Fhbimg.b0.upaiyun.com%2Fba812d6615154ccdb93a25bd2aed4547b281cd30288ae-DqLihX_fw658&rpstart=0&rpnum=0&adpicid=0&force=undefined
theme_color: 546E7A

google_analytics:
# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: " "

#MathJax switch
MathJax: false

#install emoji
plugins:
  - jemoji

# social account
image:
twitter:
  username:
#  site:
facebook:
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
